# SQL Assignment 2.

Name - Anurag Chandra
Technical - AFDP 2026 Path 2 

## TASK 1

### What do the NULL rows in the result mean? How do you distinguish a ROLLUP-generated NULL from a real NULL?

* NULL rows generated by ROLLUP represent subtotals or the grand total.
* Use the GROUPING() function to distinguish them from actual NULL values in the data.

### How does CUBE differ from ROLLUP? When would you use each?
* ROLLUP creates hierarchical totals (subtotals and a grand total).
* CUBE creates all possible combinations of subtotals.
* Use ROLLUP for hierarchical reports and CUBE for multidimensional analysis.

### What is the execution order of SELECT, FROM, WHERE, GROUP BY, HAVING, ORDER BY? Why does this order matter when writing aggregation queries?
* Execution order: 
 FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY
* This matters because filtering with WHERE happens before grouping, while HAVING filters groups after aggregation.

## TASK 2

### What does PIVOT actually do internally? Could you achieve the same result with CASE + GROUP BY? Which is more readable?
* PIVOT converts row values into columns using an aggregate function.
* The same result can be achieved using CASE with GROUP BY.
* PIVOT is usually more readable for cross-tab reports.

## TASK 3

### When is UNPIVOT useful in real-world scenarios?
* UNPIVOT converts columns into rows.
* It is useful for reporting, charting, importing data, and converting wide tables into a normalized format.

### Which approach do you prefer and why?
* I prefer CROSS APPLY with VALUES because it is more flexible easier to customize, and works well with calculated values.

## TASK 4

### When would you use RIGHT JOIN vs LEFT JOIN? Is one preferred?
* RIGHT JOIN returns all rows from the right table.
* LEFT JOIN returns all rows from the left table.
* LEFT JOIN is generally preferred because it is easier to read and is more commonly used.

### What real-world scenario needs a FULL OUTER JOIN?
* FULL OUTER JOIN is useful when comparing two datasets and finding matching as well as unmatched records in both tables, such as comparing employees from two different systems.

### What is CROSS JOIN useful for? Why is it dangerous on large tables?
* CROSS JOIN generates every possible combination of rows.
* It is useful for creating combinations or test data.
* It is dangerous on large tables because the number of rows grows very quickly.

## TASK 5

### Which is most readable? Which performs best? When would you choose each?
* JOIN is usually the fastest and most efficient.
* CTE improves readability for complex queries.
* Correlated subqueries are useful for row-by-row calculations but can be slower on large datasets.

## TASK 6

### Which approach do you prefer and why?
* I prefer NOT EXISTS because it clearly expresses the logic and usually performs better than LEFT JOIN with IS NULL.

## TASK 7

### What is the difference between a CTE and a derived table? 

* A derived table exists only inside one FROM clause.
* A CTE is defined before the main query and can be referenced multiple times.

### Can a CTE reference itself? What is the readability advantage?

* A recursive CTE can reference itself.
* CTEs improve readability by breaking complex queries into smaller parts.

## TASK 8

### What are the anchor and recursive members? What is MAXRECURSION?

* The anchor member returns the starting rows.
* The recursive member repeatedly adds new rows until the condition is met.
* MAXRECURSION limits the number of recursive iterations.
* The default is 100 to prevent infinite recursion.
* Increase it for deeper hierarchies or lower it to catch recursion errors.

## TASK 9

### How is a derived table different from a CTE and a temp table?
* A derived table exists only within one query.
* A CTE also exists for one statement but improves readability.
* A temp table is stored in tempdb and can be reused across multiple statements.

## TASK 10

### When should you use a View vs writing the JOIN query directly? Can you INSERT into a View?
* Use a view when the same query is used repeatedly or to simplify complex joins.
* Write the JOIN directly for one-time queries.
* INSERT is possible only on simple views that map directly to a single table.

## TASK 11

### What is the difference between a schema and a database? Why is dbo the default schema? How do schemas help?
* A database stores data and database objects.
* A schema is a logical container inside a database.
* dbo is the default schema for database owners.
* Schemas help organize objects, simplify permissions, avoid name conflicts, and support large-team development.

### Grant SELECT on the Reporting schema to a test user/role

![image](/SQL_Assignment/SQL_Screenshots/GRANT.png)

## TASK 12

### What are the column-count and data-type rules? 
* All queries must return the same number of columns with compatible data types.

### How do INTERSECT and EXCEPT handle duplicates and NULLs? 
* INTERSECT and EXCEPT automatically remove duplicate rows.
* NULL values are treated as equal when comparing rows.

### When would you use them instead of joins?
* Use set operators when comparing complete result sets rather than joining tables.

## TASK 13

### Why does NULL = NULL return FALSE? How does this affect JOINs?
* NULL represents an unknown value, so NULL = NULL is not TRUE.
* Use IS NULL to test for NULL values.
* Rows with NULL join columns do not match in equality joins unless handled explicitly.